name: flutter_getx_data_cli_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: ^3.26.0
  json_annotation: ^3.0.1
  flutter_data: ^0.7.1
  path_provider: ^1.6.7
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true